"""Add user currency code

Revision ID: 1b4847e7143e
Revises: c324573231fe
Create Date: 2026-08-03 18:50:14.708668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4847e7143e'
down_revision: Union[str, None] = 'c324573231fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ai_runs_created_by_user_id'), 'ai_runs', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_decisions_decided_by_user_id'), 'decisions', ['decided_by_user_id'], unique=False)
    op.drop_index('uq_primary_kpi', table_name='initiative_metrics', postgresql_where="(((role)::text = 'PRIMARY_KPI'::text) AND ((status)::text <> 'SUPERSEDED'::text))")
    op.create_index(op.f('ix_learnings_created_by_user_id'), 'learnings', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_outcomes_validated_by_user_id'), 'outcomes', ['validated_by_user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_ai_run_id'), 'recommendations', ['ai_run_id'], unique=False)
    op.create_index(op.f('ix_review_snapshots_initiative_id'), 'review_snapshots', ['initiative_id'], unique=False)
    op.drop_constraint('fk_snapshots_review_composite', 'review_snapshots', type_='foreignkey')
    op.add_column('users', sa.Column('currency_code', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency_code')
    op.create_foreign_key('fk_snapshots_review_composite', 'review_snapshots', 'reviews', ['organization_id', 'review_id'], ['organization_id', 'id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_review_snapshots_initiative_id'), table_name='review_snapshots')
    op.drop_index(op.f('ix_recommendations_ai_run_id'), table_name='recommendations')
    op.drop_index(op.f('ix_outcomes_validated_by_user_id'), table_name='outcomes')
    op.drop_index(op.f('ix_learnings_created_by_user_id'), table_name='learnings')
    op.create_index('uq_primary_kpi', 'initiative_metrics', ['initiative_id'], unique=True, postgresql_where="(((role)::text = 'PRIMARY_KPI'::text) AND ((status)::text <> 'SUPERSEDED'::text))")
    op.drop_index(op.f('ix_decisions_decided_by_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_ai_runs_created_by_user_id'), table_name='ai_runs')
    # ### end Alembic commands ###
