"""create_evidence_and_review_tables

Revision ID: 46b62ed6bc01
Revises: e3f613206e19
Create Date: 2026-07-30 10:49:15.499853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46b62ed6bc01'
down_revision: Union[str, None] = 'e3f613206e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_initiative_versions_tenant', 'initiative_versions', ['organization_id', 'id'])
    op.create_unique_constraint('uq_investments_tenant', 'investments', ['organization_id', 'id'])
    op.create_unique_constraint('uq_observations_tenant', 'observations', ['organization_id', 'id'])
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("claim_type IN ('DESCRIPTIVE', 'CHANGE', 'ASSOCIATION', 'ATTRIBUTION', 'CAUSAL', 'FINANCIAL_VALUE', 'DECISION')", name='chk_claim_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'ACTIVE', 'RETIRED')", name='chk_claim_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_claims_initiative_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_claims_tenant')
    )
    op.create_index(op.f('ix_claims_created_by_user_id'), 'claims', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_claims_initiative_id'), 'claims', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_claims_organization_id'), 'claims', ['organization_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action_type IN ('ROUTING_CHANGE', 'SCOPE_CHANGE', 'BUDGET_CHANGE', 'PROCESS_CHANGE', 'OTHER')", name='chk_intervention_type'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_interventions_initiative_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_interventions_tenant')
    )
    op.create_index(op.f('ix_interventions_created_by_user_id'), 'interventions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_interventions_initiative_id'), 'interventions', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_interventions_organization_id'), 'interventions', ['organization_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_question', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("review_type IN ('INVESTMENT', 'SCHEDULED', 'EXCEPTION', 'POST_DECISION')", name='chk_review_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'READY', 'IN_REVIEW', 'COMPLETED', 'CANCELLED')", name='chk_review_status'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_reviews_initiative_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_reviews_tenant')
    )
    op.create_index(op.f('ix_reviews_initiative_id'), 'reviews', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_reviews_organization_id'), 'reviews', ['organization_id'], unique=False)
    op.create_table('evidence_strength_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confounders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method_version', sa.String(length=50), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("state IN ('LIMITED', 'MODERATE', 'STRONG')", name='chk_strength_state'),
    sa.ForeignKeyConstraint(['organization_id', 'claim_id'], ['claims.organization_id', 'claims.id'], name='fk_strength_claim_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_strength_tenant')
    )
    op.create_index(op.f('ix_evidence_strength_assessments_claim_id'), 'evidence_strength_assessments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_strength_assessments_organization_id'), 'evidence_strength_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_strength_assessments_reviewed_by_user_id'), 'evidence_strength_assessments', ['reviewed_by_user_id'], unique=False)
    op.create_table('review_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('initiative_version_id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=True),
    sa.Column('measurement_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_version_id'], ['initiative_versions.organization_id', 'initiative_versions.id'], name='fk_snapshots_init_version_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'investment_id'], ['investments.organization_id', 'investments.id'], name='fk_snapshots_investment_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'review_id'], ['reviews.organization_id', 'reviews.id'], name='fk_snapshots_review_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'review_id', 'snapshot_version', name='uq_review_snapshots_tenant')
    )
    op.create_index(op.f('ix_review_snapshots_initiative_version_id'), 'review_snapshots', ['initiative_version_id'], unique=False)
    op.create_index(op.f('ix_review_snapshots_investment_id'), 'review_snapshots', ['investment_id'], unique=False)
    op.create_index(op.f('ix_review_snapshots_organization_id'), 'review_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_review_snapshots_review_id'), 'review_snapshots', ['review_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_level', sa.String(length=10), nullable=False),
    sa.Column('stance', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_state', sa.String(length=50), nullable=False),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source_type = 'OBSERVATION' AND observation_id IS NOT NULL AND source_file_id IS NULL) OR (source_type = 'FILE' AND source_file_id IS NOT NULL AND observation_id IS NULL) OR (source_type NOT IN ('OBSERVATION', 'FILE') AND observation_id IS NULL AND source_file_id IS NULL)", name='chk_evidence_source_type_invariants'),
    sa.CheckConstraint("evidence_level IN ('E0', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6')", name='chk_evidence_level'),
    sa.CheckConstraint("stance IN ('SUPPORTS', 'CONFLICTS', 'CONTEXT')", name='chk_evidence_stance'),
    sa.CheckConstraint("validation_state IN ('UNVALIDATED', 'VALIDATED', 'REJECTED')", name='chk_evidence_validation'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'claim_id'], ['claims.organization_id', 'claims.id'], name='fk_evidence_claim_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_evidence_initiative_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'observation_id'], ['observations.organization_id', 'observations.id'], name='fk_evidence_observation_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'source_file_id'], ['source_files.organization_id', 'source_files.id'], name='fk_evidence_source_file_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_evidence_tenant')
    )
    op.create_index(op.f('ix_evidence_claim_id'), 'evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_created_by_user_id'), 'evidence', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_evidence_initiative_id'), 'evidence', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_evidence_observation_id'), 'evidence', ['observation_id'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_file_id'), 'evidence', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_evidence_validated_by_user_id'), 'evidence', ['validated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_validated_by_user_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source_file_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_observation_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_initiative_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_by_user_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_claim_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_review_snapshots_review_id'), table_name='review_snapshots')
    op.drop_index(op.f('ix_review_snapshots_organization_id'), table_name='review_snapshots')
    op.drop_index(op.f('ix_review_snapshots_investment_id'), table_name='review_snapshots')
    op.drop_index(op.f('ix_review_snapshots_initiative_version_id'), table_name='review_snapshots')
    op.drop_table('review_snapshots')
    op.drop_index(op.f('ix_evidence_strength_assessments_reviewed_by_user_id'), table_name='evidence_strength_assessments')
    op.drop_index(op.f('ix_evidence_strength_assessments_organization_id'), table_name='evidence_strength_assessments')
    op.drop_index(op.f('ix_evidence_strength_assessments_claim_id'), table_name='evidence_strength_assessments')
    op.drop_table('evidence_strength_assessments')
    op.drop_index(op.f('ix_reviews_organization_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_initiative_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_interventions_organization_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_initiative_id'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_created_by_user_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_claims_organization_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_initiative_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_created_by_user_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_constraint('uq_observations_tenant', 'observations', type_='unique')
    op.drop_constraint('uq_investments_tenant', 'investments', type_='unique')
    op.drop_constraint('uq_initiative_versions_tenant', 'initiative_versions', type_='unique')
    # ### end Alembic commands ###
