"""create_initiative_and_measurement_tables

Revision ID: 51ab255d88b1
Revises: 001
Create Date: 2026-07-29 22:25:18.602212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ab255d88b1'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_area', sa.String(length=255), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('problem_statement', sa.String(), nullable=True),
    sa.Column('proposed_intervention', sa.String(), nullable=True),
    sa.Column('expected_business_outcome', sa.String(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle_state IN ('DRAFT', 'SUBMITTED', 'ACTIVE', 'COMPLETED', 'ABANDONED')", name='chk_initiatives_lifecycle'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_initiatives_tenant')
    )
    op.create_index(op.f('ix_initiatives_created_by_user_id'), 'initiatives', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_initiatives_organization_id'), 'initiatives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_initiatives_owner_user_id'), 'initiatives', ['owner_user_id'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'canonical_key', name='uq_metric_canonical_key'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_metric_defs_tenant')
    )
    op.create_index(op.f('ix_metric_definitions_organization_id'), 'metric_definitions', ['organization_id'], unique=False)
    op.create_table('initiative_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('business_case_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_number > 0', name='chk_init_versions_num'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_init_versions_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiative_id', 'version_number', name='uq_initiative_version')
    )
    op.create_index(op.f('ix_initiative_versions_created_by_user_id'), 'initiative_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_initiative_versions_initiative_id'), 'initiative_versions', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_initiative_versions_organization_id'), 'initiative_versions', ['organization_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='chk_investments_currency'),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'SUPERSEDED')", name='chk_investments_status'),
    sa.CheckConstraint('version_number > 0', name='chk_investments_version'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_investments_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiative_id', 'version_number', name='uq_investment_version'),
    sa.UniqueConstraint('organization_id', 'id', 'currency', name='uq_investments_tenant_currency')
    )
    op.create_index(op.f('ix_investments_created_by_user_id'), 'investments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_investments_initiative_id'), 'investments', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_investments_organization_id'), 'investments', ['organization_id'], unique=False)
    op.create_table('metric_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_definition_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('improvement_direction', sa.String(length=50), nullable=False),
    sa.Column('aggregation_method', sa.String(length=50), nullable=False),
    sa.Column('formula_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_grain', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("aggregation_method IN ('SUM', 'AVG', 'RATIO', 'CUSTOM')", name='chk_metric_agg_method'),
    sa.CheckConstraint("improvement_direction IN ('INCREASE', 'DECREASE', 'RANGE', 'NONE')", name='chk_metric_direction'),
    sa.CheckConstraint("time_grain IN ('DAY', 'WEEK', 'MONTH', 'REVIEW_PERIOD')", name='chk_metric_time_grain'),
    sa.CheckConstraint("value_type IN ('DECIMAL', 'INTEGER', 'MONEY', 'PERCENT', 'DURATION')", name='chk_metric_value_type'),
    sa.CheckConstraint('version_number > 0', name='chk_metric_v_num'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'metric_definition_id'], ['metric_definitions.organization_id', 'metric_definitions.id'], name='fk_metric_versions_parent', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_definition_id', 'version_number', name='uq_metric_version_number'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_metric_versions_tenant')
    )
    op.create_index(op.f('ix_metric_versions_created_by_user_id'), 'metric_versions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_metric_versions_metric_definition_id'), 'metric_versions', ['metric_definition_id'], unique=False)
    op.create_index(op.f('ix_metric_versions_organization_id'), 'metric_versions', ['organization_id'], unique=False)
    op.create_table('initiative_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('metric_version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('target_lower', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('target_upper', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_operator', sa.String(length=50), nullable=True),
    sa.Column('review_period', sa.String(length=100), nullable=True),
    sa.Column('validator_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(target_type = 'ABSOLUTE' AND target_value IS NOT NULL AND target_lower IS NULL AND target_upper IS NULL) OR (target_type = 'RELATIVE' AND target_value IS NOT NULL AND target_lower IS NULL AND target_upper IS NULL) OR (target_type = 'RANGE' AND target_lower IS NOT NULL AND target_upper IS NOT NULL AND target_lower <= target_upper AND target_value IS NULL) OR (target_type = 'DIRECTIONAL' AND target_value IS NULL AND target_lower IS NULL AND target_upper IS NULL)", name='chk_target_values_match_type'),
    sa.CheckConstraint("(threshold_operator = 'BETWEEN' AND target_lower IS NOT NULL AND target_upper IS NOT NULL AND target_lower <= target_upper) OR (threshold_operator != 'BETWEEN' OR threshold_operator IS NULL)", name='chk_between_operator_bounds'),
    sa.CheckConstraint("role IN ('PRIMARY_KPI', 'GUARDRAIL', 'SECONDARY', 'CONTEXT')", name='chk_init_metric_role'),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'SUPERSEDED')", name='chk_init_metric_status'),
    sa.CheckConstraint("target_type IN ('ABSOLUTE', 'RELATIVE', 'RANGE', 'DIRECTIONAL')", name='chk_init_metric_target'),
    sa.CheckConstraint("threshold_operator IN ('GREATER_THAN', 'LESS_THAN', 'GREATER_EQUAL', 'LESS_EQUAL', 'EQUAL', 'BETWEEN')", name='chk_init_metric_operator'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_id'], ['initiatives.organization_id', 'initiatives.id'], name='fk_init_metrics_initiative', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'metric_version_id'], ['metric_versions.organization_id', 'metric_versions.id'], name='fk_init_metrics_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_initiative_metrics_tenant')
    )
    op.create_index(op.f('ix_initiative_metrics_initiative_id'), 'initiative_metrics', ['initiative_id'], unique=False)
    op.create_index('uq_primary_kpi', 'initiative_metrics', ['initiative_id'], unique=True, postgresql_where="role = 'PRIMARY_KPI'")
    op.create_index(op.f('ix_initiative_metrics_metric_version_id'), 'initiative_metrics', ['metric_version_id'], unique=False)
    op.create_index(op.f('ix_initiative_metrics_organization_id'), 'initiative_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_initiative_metrics_validator_user_id'), 'initiative_metrics', ['validator_user_id'], unique=False)
    op.create_table('investment_cost_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recurrence', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('assumption_note', sa.String(), nullable=True),
    sa.CheckConstraint("category IN ('SOFTWARE', 'INFRASTRUCTURE', 'LABOR', 'OTHER')", name='chk_cost_category'),
    sa.CheckConstraint("recurrence IN ('ONE_TIME', 'MONTHLY', 'ANNUAL')", name='chk_cost_recurrence'),
    sa.CheckConstraint("value_type IN ('PLANNED', 'ACTUAL', 'MODELED')", name='chk_cost_value_type'),
    sa.CheckConstraint('amount >= 0.00', name='chk_cost_items_amount'),
    sa.ForeignKeyConstraint(['organization_id', 'investment_id', 'currency'], ['investments.organization_id', 'investments.id', 'investments.currency'], name='fk_cost_items_parent', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_cost_items_investment_id'), 'investment_cost_items', ['investment_id'], unique=False)
    op.create_index(op.f('ix_investment_cost_items_organization_id'), 'investment_cost_items', ['organization_id'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_metric_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_type', sa.String(length=50), nullable=False),
    sa.Column('source_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'DRAFT' AND approved_by_user_id IS NULL AND approved_at IS NULL) OR (status = 'APPROVED' AND approved_by_user_id IS NOT NULL AND approved_at IS NOT NULL) OR (status = 'SUPERSEDED')", name='chk_baseline_approval_consistency'),
    sa.CheckConstraint("baseline_type IN ('PRE_DEPLOYMENT', 'RECONSTRUCTED', 'OTHER')", name='chk_baselines_type'),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED', 'SUPERSEDED')", name='chk_baselines_status'),
    sa.CheckConstraint('period_end > period_start', name='chk_baselines_dates'),
    sa.CheckConstraint('version_number > 0', name='chk_baselines_version'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_metric_id'], ['initiative_metrics.organization_id', 'initiative_metrics.id'], name='fk_baselines_parent', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiative_metric_id', 'version_number', name='uq_baseline_version')
    )
    op.create_index(op.f('ix_baselines_approved_by_user_id'), 'baselines', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_baselines_initiative_metric_id'), 'baselines', ['initiative_metric_id'], unique=False)
    op.create_index(op.f('ix_baselines_organization_id'), 'baselines', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baselines_organization_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_initiative_metric_id'), table_name='baselines')
    op.drop_index(op.f('ix_baselines_approved_by_user_id'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_investment_cost_items_organization_id'), table_name='investment_cost_items')
    op.drop_index(op.f('ix_investment_cost_items_investment_id'), table_name='investment_cost_items')
    op.drop_table('investment_cost_items')
    op.drop_index(op.f('ix_initiative_metrics_validator_user_id'), table_name='initiative_metrics')
    op.drop_index(op.f('ix_initiative_metrics_organization_id'), table_name='initiative_metrics')
    op.drop_index(op.f('ix_initiative_metrics_metric_version_id'), table_name='initiative_metrics')
    op.drop_index(op.f('ix_initiative_metrics_initiative_id'), table_name='initiative_metrics')
    op.drop_index('uq_primary_kpi', table_name='initiative_metrics')
    op.drop_table('initiative_metrics')
    op.drop_index(op.f('ix_metric_versions_organization_id'), table_name='metric_versions')
    op.drop_index(op.f('ix_metric_versions_metric_definition_id'), table_name='metric_versions')
    op.drop_index(op.f('ix_metric_versions_created_by_user_id'), table_name='metric_versions')
    op.drop_table('metric_versions')
    op.drop_index(op.f('ix_investments_organization_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_initiative_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_created_by_user_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_initiative_versions_organization_id'), table_name='initiative_versions')
    op.drop_index(op.f('ix_initiative_versions_initiative_id'), table_name='initiative_versions')
    op.drop_index(op.f('ix_initiative_versions_created_by_user_id'), table_name='initiative_versions')
    op.drop_table('initiative_versions')
    op.drop_index(op.f('ix_metric_definitions_organization_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_initiatives_owner_user_id'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_organization_id'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_created_by_user_id'), table_name='initiatives')
    op.drop_table('initiatives')
    # ### end Alembic commands ###
