"""create_data_ingestion_and_analytics_tables

Revision ID: e3f613206e19
Revises: 51ab255d88b1
Create Date: 2026-07-29 22:51:03.193120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f613206e19'
down_revision: Union[str, None] = '51ab255d88b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_init_metrics_composite_attrs', 'initiative_metrics', ['organization_id', 'id', 'metric_version_id', 'initiative_id'])
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('health_state', sa.String(length=50), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("health_state IN ('HEALTHY', 'PARTIAL', 'STALE', 'BLOCKED', 'UNKNOWN')", name='chk_source_health'),
    sa.CheckConstraint("source_type IN ('CSV', 'PARQUET', 'MANUAL', 'CONNECTOR')", name='chk_source_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_data_sources_tenant')
    )
    op.create_index(op.f('ix_data_sources_organization_id'), 'data_sources', ['organization_id'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('size_bytes > 0', name='chk_file_size'),
    sa.ForeignKeyConstraint(['organization_id', 'data_source_id'], ['data_sources.organization_id', 'data_sources.id'], name='fk_source_files_data_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'data_source_id', 'checksum', name='uq_source_files_checksum'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_source_files_tenant')
    )
    op.create_index(op.f('ix_source_files_data_source_id'), 'source_files', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_files_organization_id'), 'source_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_source_files_uploaded_by_user_id'), 'source_files', ['uploaded_by_user_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('source_file_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('mapping_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED')", name='chk_ingestion_status'),
    sa.CheckConstraint('rows_received >= 0 AND rows_accepted >= 0 AND rows_rejected >= 0 AND rows_accepted + rows_rejected <= rows_received', name='chk_ingestion_rows_invariants'),
    sa.ForeignKeyConstraint(['organization_id', 'data_source_id'], ['data_sources.organization_id', 'data_sources.id'], name='fk_ingestion_runs_data_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'source_file_id'], ['source_files.organization_id', 'source_files.id'], name='fk_ingestion_runs_source_file', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'data_source_id', 'idempotency_key', name='uq_ingestion_runs_idempotency'),
    sa.UniqueConstraint('organization_id', 'id', name='uq_ingestion_runs_tenant')
    )
    op.create_index(op.f('ix_ingestion_runs_data_source_id'), 'ingestion_runs', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_organization_id'), 'ingestion_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_file_id'), 'ingestion_runs', ['source_file_id'], unique=False)
    op.create_table('data_quality_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=True),
    sa.Column('initiative_metric_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('completeness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('freshness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consistency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method_version', sa.String(length=50), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('HEALTHY', 'PARTIAL', 'STALE', 'BLOCKED')", name='chk_quality_state'),
    sa.CheckConstraint('(data_source_id IS NOT NULL)::int + (ingestion_run_id IS NOT NULL)::int + (initiative_metric_id IS NOT NULL)::int = 1', name='chk_dq_single_target'),
    sa.ForeignKeyConstraint(['organization_id', 'data_source_id'], ['data_sources.organization_id', 'data_sources.id'], name='fk_dq_data_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'ingestion_run_id'], ['ingestion_runs.organization_id', 'ingestion_runs.id'], name='fk_dq_ingestion_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_metric_id'], ['initiative_metrics.organization_id', 'initiative_metrics.id'], name='fk_dq_initiative_metric', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_assessments_data_source_id'), 'data_quality_assessments', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_ingestion_run_id'), 'data_quality_assessments', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_initiative_metric_id'), 'data_quality_assessments', ['initiative_metric_id'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_organization_id'), 'data_quality_assessments', ['organization_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_metric_id', sa.Uuid(), nullable=False),
    sa.Column('metric_version_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('ingestion_run_id', sa.Uuid(), nullable=True),
    sa.Column('source_row_index', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observation_type', sa.String(length=50), nullable=False),
    sa.Column('calculation_version', sa.String(length=100), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('validation_state', sa.String(length=50), nullable=False),
    sa.Column('validated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(observation_type = 'MANUAL' AND ingestion_run_id IS NULL AND source_row_index IS NULL AND data_source_id IS NULL) OR (observation_type != 'MANUAL')", name='chk_manual_lineage_guard'),
    sa.CheckConstraint("observation_type IN ('OBSERVED', 'DERIVED', 'RECONSTRUCTED', 'MANUAL')", name='chk_observations_type'),
    sa.CheckConstraint("validation_state IN ('UNVALIDATED', 'VALIDATED', 'REJECTED')", name='chk_observations_validation'),
    sa.CheckConstraint('period_end >= period_start', name='chk_observations_dates'),
    sa.CheckConstraint('source_row_index >= 0 OR source_row_index IS NULL', name='chk_observation_row_index'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id', 'data_source_id'], ['data_sources.organization_id', 'data_sources.id'], name='fk_observations_data_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'ingestion_run_id'], ['ingestion_runs.organization_id', 'ingestion_runs.id'], name='fk_observations_ingestion_run', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'initiative_metric_id', 'metric_version_id', 'initiative_id'], ['initiative_metrics.organization_id', 'initiative_metrics.id', 'initiative_metrics.metric_version_id', 'initiative_metrics.initiative_id'], name='fk_observations_init_metric_composite', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'source_row_index', name='uq_observations_source_row')
    )
    op.create_index(op.f('ix_observations_created_by_user_id'), 'observations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_observations_data_source_id'), 'observations', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_observations_ingestion_run_id'), 'observations', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_observations_initiative_id'), 'observations', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_observations_initiative_metric_id'), 'observations', ['initiative_metric_id'], unique=False)
    op.create_index(op.f('ix_observations_metric_version_id'), 'observations', ['metric_version_id'], unique=False)
    op.create_index(op.f('ix_observations_organization_id'), 'observations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_observations_validated_by_user_id'), 'observations', ['validated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_validated_by_user_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_organization_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_metric_version_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_initiative_metric_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_initiative_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_ingestion_run_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_data_source_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_created_by_user_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_data_quality_assessments_organization_id'), table_name='data_quality_assessments')
    op.drop_index(op.f('ix_data_quality_assessments_initiative_metric_id'), table_name='data_quality_assessments')
    op.drop_index(op.f('ix_data_quality_assessments_ingestion_run_id'), table_name='data_quality_assessments')
    op.drop_index(op.f('ix_data_quality_assessments_data_source_id'), table_name='data_quality_assessments')
    op.drop_table('data_quality_assessments')
    op.drop_index(op.f('ix_ingestion_runs_source_file_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_organization_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_data_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_source_files_uploaded_by_user_id'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_organization_id'), table_name='source_files')
    op.drop_index(op.f('ix_source_files_data_source_id'), table_name='source_files')
    op.drop_table('source_files')
    op.drop_index(op.f('ix_data_sources_organization_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_constraint('uq_init_metrics_composite_attrs', 'initiative_metrics', type_='unique')
    # ### end Alembic commands ###
